channels:
  - conda-forge
  - r
  - bioconda
dependencies:
  - r-tidyverse
  - r-rcolorbrewer
  - r-patchwork
  - r-igraph
  - r-ggnewscale
  - r-desctools
  - r-ggmsa
  - r-janitor
  - r-ggpubr
  - r-logistf
  - r-micropan
  - r-caret
